import type { Medicine } from "../types/medicine";
import { computeStatus, todayISO } from "./date-utils";

function addDays(isoDate: string, days: number): string {
  const d = new Date(isoDate);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

const today = todayISO();

export const SAMPLE_MEDICINES: Medicine[] = [
  {
    id: 1001,
    name: "Metformin 500mg",
    expiryDate: addDays(today, 180),
    batchNumber: "MET-2024-001",
    manufacturer: "Sun Pharma",
    dosage: "500 mg",
    quantity: 142,
    notes: "Type 2 diabetes management",
    status: computeStatus(addDays(today, 180)),
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 1002,
    name: "Amlodipine 5mg",
    expiryDate: addDays(today, 4),
    batchNumber: "AML-2024-047",
    manufacturer: "Cipla Ltd",
    dosage: "5 mg",
    quantity: 33,
    notes: "Hypertension treatment",
    status: computeStatus(addDays(today, 4)),
    createdAt: Date.now() - 86400000 * 60,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 1003,
    name: "Atorvastatin 10mg",
    expiryDate: addDays(today, -15),
    batchNumber: "ATV-2023-112",
    manufacturer: "Dr. Reddy's",
    dosage: "10 mg",
    quantity: 16,
    notes: "Cholesterol management — EXPIRED",
    status: computeStatus(addDays(today, -15)),
    createdAt: Date.now() - 86400000 * 90,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: 1004,
    name: "Pantoprazole 40mg",
    expiryDate: addDays(today, 5),
    batchNumber: "PAN-2024-088",
    manufacturer: "Zydus Cadila",
    dosage: "40 mg",
    quantity: 32,
    notes: "Acid reflux treatment",
    status: computeStatus(addDays(today, 5)),
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 1005,
    name: "Cetirizine 10mg",
    expiryDate: addDays(today, 210),
    batchNumber: "CET-2024-033",
    manufacturer: "Mankind Pharma",
    dosage: "10 mg",
    quantity: 88,
    notes: "Antihistamine for allergies",
    status: computeStatus(addDays(today, 210)),
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: 1006,
    name: "Azithromycin 500mg",
    expiryDate: addDays(today, -30),
    batchNumber: "AZT-2023-099",
    manufacturer: "Aurobindo Pharma",
    dosage: "500 mg",
    quantity: 2,
    notes: "Antibiotic — EXPIRED",
    status: computeStatus(addDays(today, -30)),
    createdAt: Date.now() - 86400000 * 120,
    updatedAt: Date.now() - 86400000 * 10,
  },
  {
    id: 1007,
    name: "Ibuprofen 400mg",
    expiryDate: addDays(today, 6),
    batchNumber: "IBU-2024-055",
    manufacturer: "Abbott India",
    dosage: "400 mg",
    quantity: 16,
    notes: "Pain and fever relief",
    status: computeStatus(addDays(today, 6)),
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 1008,
    name: "Lisinopril 5mg",
    expiryDate: addDays(today, 365),
    batchNumber: "LIS-2025-001",
    manufacturer: "Torrent Pharma",
    dosage: "5 mg",
    quantity: 60,
    notes: "ACE inhibitor for blood pressure",
    status: computeStatus(addDays(today, 365)),
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 1009,
    name: "Vitamin D3 1000IU",
    expiryDate: addDays(today, 3),
    batchNumber: "VIT-2024-077",
    manufacturer: "HealthKart",
    dosage: "1000 IU",
    quantity: 45,
    notes: "Vitamin supplement",
    status: computeStatus(addDays(today, 3)),
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 1010,
    name: "Omeprazole 20mg",
    expiryDate: addDays(today, 90),
    batchNumber: "OMP-2024-122",
    manufacturer: "Lupin Ltd",
    dosage: "20 mg",
    quantity: 75,
    notes: "Proton pump inhibitor",
    status: computeStatus(addDays(today, 90)),
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
  },
].map((m) => ({ ...m, status: computeStatus(m.expiryDate) }));
