/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddMedicineRequest {
  'manufacturer' : string,
  'expiryDate' : string,
  'name' : string,
  'notes' : string,
  'batchNumber' : string,
}
export type AuthResult = {
    'ok' : { 'token' : SessionToken, 'user' : UserInfo }
  } |
  { 'err' : string };
export interface Medicine {
  'id' : bigint,
  'manufacturer' : string,
  'expiryDate' : string,
  'userId' : UserId,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'notes' : string,
  'batchNumber' : string,
}
export type MedicineResult = { 'ok' : Medicine } |
  { 'err' : string };
export type MedicinesResult = { 'ok' : Array<Medicine> } |
  { 'err' : string };
export type SessionToken = string;
export interface UpdateMedicineRequest {
  'id' : bigint,
  'manufacturer' : string,
  'expiryDate' : string,
  'name' : string,
  'notes' : string,
  'batchNumber' : string,
}
export type UserId = string;
export interface UserInfo {
  'id' : UserId,
  'username' : string,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export interface _SERVICE {
  'addMedicine' : ActorMethod<
    [SessionToken, AddMedicineRequest],
    MedicineResult
  >,
  'deleteMedicine' : ActorMethod<
    [SessionToken, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'filterByStatus' : ActorMethod<[SessionToken, string], MedicinesResult>,
  'getDashboardStats' : ActorMethod<
    [SessionToken],
    {
      'nearExpiry' : bigint,
      'total' : bigint,
      'expired' : bigint,
      'safe' : bigint,
    }
  >,
  'getMedicine' : ActorMethod<[SessionToken, bigint], [] | [Medicine]>,
  'getMedicines' : ActorMethod<[SessionToken], MedicinesResult>,
  'getRecentActivity' : ActorMethod<[SessionToken], Array<Medicine>>,
  'login' : ActorMethod<[string, string], AuthResult>,
  'logout' : ActorMethod<[SessionToken], undefined>,
  'register' : ActorMethod<[string, string], AuthResult>,
  'searchMedicines' : ActorMethod<[SessionToken, string], MedicinesResult>,
  'updateMedicine' : ActorMethod<
    [SessionToken, UpdateMedicineRequest],
    MedicineResult
  >,
  'whoAmI' : ActorMethod<[SessionToken], [] | [UserInfo]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];