/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Text;
export const AddMedicineRequest = IDL.Record({
  'manufacturer' : IDL.Text,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'batchNumber' : IDL.Text,
});
export const UserId = IDL.Text;
export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'expiryDate' : IDL.Text,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'batchNumber' : IDL.Text,
});
export const MedicineResult = IDL.Variant({
  'ok' : Medicine,
  'err' : IDL.Text,
});
export const MedicinesResult = IDL.Variant({
  'ok' : IDL.Vec(Medicine),
  'err' : IDL.Text,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserInfo = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'role' : UserRole,
});
export const AuthResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : SessionToken, 'user' : UserInfo }),
  'err' : IDL.Text,
});
export const UpdateMedicineRequest = IDL.Record({
  'id' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'batchNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMedicine' : IDL.Func(
      [SessionToken, AddMedicineRequest],
      [MedicineResult],
      [],
    ),
  'deleteMedicine' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'filterByStatus' : IDL.Func([SessionToken, IDL.Text], [MedicinesResult], []),
  'getDashboardStats' : IDL.Func(
      [SessionToken],
      [
        IDL.Record({
          'nearExpiry' : IDL.Nat,
          'total' : IDL.Nat,
          'expired' : IDL.Nat,
          'safe' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getMedicine' : IDL.Func([SessionToken, IDL.Nat], [IDL.Opt(Medicine)], []),
  'getMedicines' : IDL.Func([SessionToken], [MedicinesResult], []),
  'getRecentActivity' : IDL.Func([SessionToken], [IDL.Vec(Medicine)], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'logout' : IDL.Func([SessionToken], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'searchMedicines' : IDL.Func([SessionToken, IDL.Text], [MedicinesResult], []),
  'updateMedicine' : IDL.Func(
      [SessionToken, UpdateMedicineRequest],
      [MedicineResult],
      [],
    ),
  'whoAmI' : IDL.Func([SessionToken], [IDL.Opt(UserInfo)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Text;
  const AddMedicineRequest = IDL.Record({
    'manufacturer' : IDL.Text,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'batchNumber' : IDL.Text,
  });
  const UserId = IDL.Text;
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'expiryDate' : IDL.Text,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'batchNumber' : IDL.Text,
  });
  const MedicineResult = IDL.Variant({ 'ok' : Medicine, 'err' : IDL.Text });
  const MedicinesResult = IDL.Variant({
    'ok' : IDL.Vec(Medicine),
    'err' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserInfo = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'role' : UserRole,
  });
  const AuthResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : SessionToken, 'user' : UserInfo }),
    'err' : IDL.Text,
  });
  const UpdateMedicineRequest = IDL.Record({
    'id' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'batchNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'addMedicine' : IDL.Func(
        [SessionToken, AddMedicineRequest],
        [MedicineResult],
        [],
      ),
    'deleteMedicine' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'filterByStatus' : IDL.Func(
        [SessionToken, IDL.Text],
        [MedicinesResult],
        [],
      ),
    'getDashboardStats' : IDL.Func(
        [SessionToken],
        [
          IDL.Record({
            'nearExpiry' : IDL.Nat,
            'total' : IDL.Nat,
            'expired' : IDL.Nat,
            'safe' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getMedicine' : IDL.Func([SessionToken, IDL.Nat], [IDL.Opt(Medicine)], []),
    'getMedicines' : IDL.Func([SessionToken], [MedicinesResult], []),
    'getRecentActivity' : IDL.Func([SessionToken], [IDL.Vec(Medicine)], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'logout' : IDL.Func([SessionToken], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'searchMedicines' : IDL.Func(
        [SessionToken, IDL.Text],
        [MedicinesResult],
        [],
      ),
    'updateMedicine' : IDL.Func(
        [SessionToken, UpdateMedicineRequest],
        [MedicineResult],
        [],
      ),
    'whoAmI' : IDL.Func([SessionToken], [IDL.Opt(UserInfo)], []),
  });
};

export const init = ({ IDL }) => { return []; };