/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export interface UpdateMedicineRequest {
    id: bigint;
    manufacturer: string;
    expiryDate: string;
    name: string;
    notes: string;
    batchNumber: string;
}
export type SessionToken = string;
export type MedicineResult = {
    __kind__: "ok";
    ok: Medicine;
} | {
    __kind__: "err";
    err: string;
};
export type MedicinesResult = {
    __kind__: "ok";
    ok: Array<Medicine>;
} | {
    __kind__: "err";
    err: string;
};
export interface Medicine {
    id: bigint;
    manufacturer: string;
    expiryDate: string;
    userId: UserId;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    notes: string;
    batchNumber: string;
}
export type AuthResult = {
    __kind__: "ok";
    ok: {
        token: SessionToken;
        user: UserInfo;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface UserInfo {
    id: UserId;
    username: string;
    role: UserRole;
}
export interface AddMedicineRequest {
    manufacturer: string;
    expiryDate: string;
    name: string;
    notes: string;
    batchNumber: string;
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    addMedicine(token: SessionToken, req: AddMedicineRequest): Promise<MedicineResult>;
    deleteMedicine(token: SessionToken, id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    filterByStatus(token: SessionToken, status: string): Promise<MedicinesResult>;
    getDashboardStats(token: SessionToken): Promise<{
        nearExpiry: bigint;
        total: bigint;
        expired: bigint;
        safe: bigint;
    }>;
    getMedicine(token: SessionToken, id: bigint): Promise<Medicine | null>;
    getMedicines(token: SessionToken): Promise<MedicinesResult>;
    getRecentActivity(token: SessionToken): Promise<Array<Medicine>>;
    login(username: string, password: string): Promise<AuthResult>;
    logout(token: SessionToken): Promise<void>;
    register(username: string, password: string): Promise<AuthResult>;
    searchMedicines(token: SessionToken, term: string): Promise<MedicinesResult>;
    updateMedicine(token: SessionToken, req: UpdateMedicineRequest): Promise<MedicineResult>;
    whoAmI(token: SessionToken): Promise<UserInfo | null>;
}
import type { AuthResult as _AuthResult, Medicine as _Medicine, MedicineResult as _MedicineResult, MedicinesResult as _MedicinesResult, SessionToken as _SessionToken, UserId as _UserId, UserInfo as _UserInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMedicine(arg0: SessionToken, arg1: AddMedicineRequest): Promise<MedicineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0, arg1);
                return from_candid_MedicineResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0, arg1);
            return from_candid_MedicineResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMedicine(arg0: SessionToken, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByStatus(arg0: SessionToken, arg1: string): Promise<MedicinesResult> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByStatus(arg0, arg1);
                return from_candid_MedicinesResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByStatus(arg0, arg1);
            return from_candid_MedicinesResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: SessionToken): Promise<{
        nearExpiry: bigint;
        total: bigint;
        expired: bigint;
        safe: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getMedicine(arg0: SessionToken, arg1: bigint): Promise<Medicine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0, arg1);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0, arg1);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicines(arg0: SessionToken): Promise<MedicinesResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicines(arg0);
                return from_candid_MedicinesResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicines(arg0);
            return from_candid_MedicinesResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentActivity(arg0: SessionToken): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivity(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_AuthResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_AuthResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_AuthResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_AuthResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchMedicines(arg0: SessionToken, arg1: string): Promise<MedicinesResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMedicines(arg0, arg1);
                return from_candid_MedicinesResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMedicines(arg0, arg1);
            return from_candid_MedicinesResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMedicine(arg0: SessionToken, arg1: UpdateMedicineRequest): Promise<MedicineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, arg1);
                return from_candid_MedicineResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, arg1);
            return from_candid_MedicineResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async whoAmI(arg0: SessionToken): Promise<UserInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.whoAmI(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoAmI(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MedicineResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicineResult): MedicineResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MedicinesResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicinesResult): MedicinesResult {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserInfo]): UserInfo | null {
    return value.length === 0 ? null : from_candid_UserInfo_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Medicine]): Medicine | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    role: _UserRole;
}): {
    id: UserId;
    username: string;
    role: UserRole;
} {
    return {
        id: value.id,
        username: value.username,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: _SessionToken;
    user: _UserInfo;
}): {
    token: SessionToken;
    user: UserInfo;
} {
    return {
        token: value.token,
        user: from_candid_UserInfo_n10(_uploadFile, _downloadFile, value.user)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Medicine;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Medicine;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Medicine>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Medicine>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: _SessionToken;
        user: _UserInfo;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: SessionToken;
        user: UserInfo;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
